from Shape.AllinOne import Vertex, Shape, Isosceles, Equilateral, Scalene, Square, Rectangle, RightTriangle

if __name__ == "__main__":
   print("Hello! This is a program to create different convex shapes")
   print("Let's create a random convex shape first! (if you wish to do so, enter y, otherwhise enter n)")

   choice = str(input(""))
   given_vertices: list = []
   vertex_type: str = "x"
   user_input = 0
   x: int = 0
   y: int = 0
   if choice == "y":
      print("To stop entering vertices type \"s\" after entering the y-coordinate of the last vertex")
      conti = True
      user_input = input("Please insert the x coordinate of the first vertex in the shape: ")
      while conti == True:
         if user_input != "s":
            if vertex_type == "x":
               x = float(user_input)
               vertex_type = "y"
               user_input = input("Now, please insert the y coordinate of the vertex in the shape: ")
            else:
               y = float(user_input)
               vertex_type = "x"
               given_vertices.append(Vertex(x, y))
               user_input = input("Please insert the x coordinate of the next vertex in the shape: ")
         else:
            conti = False

      shape1 = Shape(given_vertices)
      print("The shape is regular:", shape1._is_regular)
      print("The vertices are: ", end="")
      shape1.get_shape_vertices()
      print("The edges are: ", end="")
      shape1.get_shape_edges()
      print("The inner angles are:", shape1.get_inner_angles())
      print()
   elif choice == "n":
      pass
   
   given_vertices.clear()
   print("Now let's create an isosceles triangle! (one with two sides of equal length):")
   x1 = float(input("Enter the x coordinate of the first vertex of the triangle: "))
   y1 = float(input("Enter the y coordinate of the first vertex of the triangle: "))
   given_vertices.append(Vertex(x1, y1))
   x2 = float(input("Enter the x coordinate of the second vertex of the triangle: "))
   y2 = float(input("Enter the y coordinate of the second vertex of the triangle: "))
   given_vertices.append(Vertex(x2, y2))
   x3 = float(input("Enter the x coordinate of the third vertex of the triangle: "))
   y3 = float(input("Enter the y coordinate of the third vertex of the triangle: "))
   given_vertices.append(Vertex(x3, y3))
   isosceles = Isosceles(given_vertices)
   print("The shape is regular:", isosceles._is_regular)
   print("The vertices are: ", end="")
   isosceles.get_shape_vertices()
   print("The edges are: ", end="")
   isosceles.get_shape_edges()
   print("The inner angles are:", isosceles.get_inner_angles())
   print("The area of the triangle is:", isosceles.get_area())
   print("The perimeter of the triangle is:", isosceles.get_perimeter())
   print()

   given_vertices.clear()
   print("Now let's create an equilateral triangle! (one with all of its sides of the same length)")
   x1 = float(input("Enter the x coordinate of the first vertex of the triangle: "))
   y1 = float(input("Enter the y coordinate of the first vertex of the triangle: "))
   given_vertices.append(Vertex(x1, y1))
   x2 = float(input("Enter the x coordinate of the second vertex of the triangle: "))
   y2 = float(input("Enter the y coordinate of the second vertex of the triangle: "))
   given_vertices.append(Vertex(x2, y2))
   x3 = float(input("Enter the x coordinate of the third vertex of the triangle: "))
   y3 = float(input("Enter the y coordinate of the third vertex of the triangle: "))
   given_vertices.append(Vertex(x3, y3))
   equilateral = Equilateral(given_vertices)
   print("The shape is regular:", equilateral._is_regular)
   print("The vertices are: ", end="")
   equilateral.get_shape_vertices()
   print("The edges are: ", end="")
   equilateral.get_shape_edges()
   print("The inner angles are:", equilateral.get_inner_angles())
   print("The area of the triangle is:", equilateral.get_area())
   print("The perimeter of the triangle is:", equilateral.get_perimeter())
   print()

   given_vertices.clear()
   print("Now, let's create an scalene triangle! (one with all of its sides of different length)")
   x1 = float(input("Enter the x coordinate of the first vertex of the triangle: "))
   y1 = float(input("Enter the y coordinate of the first vertex of the triangle: "))
   given_vertices.append(Vertex(x1, y1))
   x2 = float(input("Enter the x coordinate of the second vertex of the triangle: "))
   y2 = float(input("Enter the y coordinate of the second vertex of the triangle: "))
   given_vertices.append(Vertex(x2, y2))
   x3 = float(input("Enter the x coordinate of the third vertex of the triangle: "))
   y3 = float(input("Enter the y coordinate of the third vertex of the triangle: "))
   given_vertices.append(Vertex(x3, y3))
   scalene = Scalene(given_vertices)
   print("The shape is regular:", scalene._is_regular)
   print("The vertices are: ", end="")
   scalene.get_shape_vertices()
   print("The edges are: ", end="")
   scalene.get_shape_edges()
   print("The inner angles are: ", scalene.get_inner_angles())
   print("The area of the triangle is:", scalene.get_area())
   print("The perimeter of the triangle is:", scalene.get_perimeter())
   print()

   given_vertices.clear()
   print("Now, let's create a right triangle! (one with a right angle, two legs and a hypothenuse)")
   x1 = float(input("Enter the x coordinate of the first vertex of the triangle: "))
   y1 = float(input("Enter the y coordinate of the first vertex of the triangle: "))
   given_vertices.append(Vertex(x1, y1))
   x2 = float(input("Enter the x coordinate of the second vertex of the triangle: "))
   y2 = float(input("Enter the y coordinate of the second vertex of the triangle: "))
   given_vertices.append(Vertex(x2, y2))
   x3 = float(input("Enter the x coordinate of the third vertex of the triangle: "))
   y3 = float(input("Enter the y coordinate of the third vertex of the triangle: "))
   given_vertices.append(Vertex(x3, y3))
   rightTriangle = RightTriangle(given_vertices)
   print("The shape is regular:", rightTriangle._is_regular)
   print("The vertices are: ", end="")
   rightTriangle.get_shape_vertices()
   print("The edges are: ", end="")
   rightTriangle.get_shape_edges()
   print("The inner angles are:", rightTriangle.get_inner_angles())
   print("The area of the triangle is:", rightTriangle.get_area())
   print("The perimeter of the triangle is:", rightTriangle.get_perimeter())
   print()

   given_vertices.clear()
   print("Now, let's create a square! (all of its sides must have the same length)")
   x1 = float(input("Enter the x coordinate of the first vertex of the square: "))
   y1 = float(input("Enter the y coordinate of the first vertex of the square: "))
   given_vertices.append(Vertex(x1, y1))
   x2 = float(input("Enter the x coordinate of the second vertex of the square: "))
   y2 = float(input("Enter the y coordinate of the second vertex of the square: "))
   given_vertices.append(Vertex(x2, y2))
   x3 = float(input("Enter the x coordinate of the third vertex of the square: "))
   y3 = float(input("Enter the y coordinate of the third vertex of the square: "))
   given_vertices.append(Vertex(x3, y3))
   x4 = float(input("Enter the x coordinate of the third vertex of the square: "))
   y4 = float(input("Enter the y coordinate of the third vertex of the square: "))
   given_vertices.append(Vertex(x4, y4))
   square = Square(given_vertices)
   print("The shape is regular:", square._is_regular)
   print("The vertices are: ", end="")
   square.get_shape_vertices()
   print("The edges are: ", end="")
   square.get_shape_edges()
   print("The inner angles are:", square.get_inner_angles())
   print("The area of the square is:", square.get_area())
   print("The perimeter of the square is:", square.get_perimeter())
   print()

   given_vertices.clear()
   print("Now, let's create a rectangle! (a shape with two pairs of sides that must share the same length)")
   x1 = float(input("Enter the x coordinate of the first vertex of the rectangle: "))
   y1 = float(input("Enter the y coordinate of the first vertex of the rectangle: "))
   given_vertices.append(Vertex(x1, y1))
   x2 = float(input("Enter the x coordinate of the second vertex of the rectangle: "))
   y2 = float(input("Enter the y coordinate of the second vertex of the rectangle: "))
   given_vertices.append(Vertex(x2, y2))
   x3 = float(input("Enter the x coordinate of the third vertex of the rectangle: "))
   y3 = float(input("Enter the y coordinate of the third vertex of the rectangle: "))
   given_vertices.append(Vertex(x3, y3))
   x4 = float(input("Enter the x coordinate of the third vertex of the rectangle: "))
   y4 = float(input("Enter the y coordinate of the third vertex of the rectangle: "))
   given_vertices.append(Vertex(x4, y4))
   rectangle = Rectangle(given_vertices)
   print("The shape is regular:", rectangle._is_regular)
   print("The vertices are: ", end="")
   rectangle.get_shape_vertices()
   print("The edges are: ", end="")
   rectangle.get_shape_edges()
   print("The inner angles are:", rectangle.get_inner_angles())
   print("The area of the rectangle is:", rectangle.get_area())
   print("The perimeter of the rectangle is:", rectangle.get_perimeter())


